name: CI

on:
  push:
    branches:
    - 'gh-pages'
  pull_request:

jobs:
  initial_checks:
    name: Mandatory checks before CI
    runs-on: ubuntu-latest
    outputs:
      run_next: ${{ steps.skip_ci_step.outputs.run_next }}
    steps:
    # Base branch check should run whether we skip CI or not
    - name: Check base branch
      uses: pllim/action-check_pr_basebranch@main
      with:
        BASEBRANCH_NAME: gh-pages
        SKIP_BASEBRANCH_CHECK_LABEL: skip-basebranch-check
    - name: Check skip CI
      uses: OpenAstronomy/action-skip-ci@main
      id: skip_ci_step
      with:
        NO_FAIL: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # This should only run if we did not skip CI
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@ce177499ccf9fd2aded3b0426c97e5434c2e8a73
      if: steps.skip_ci_step.outputs.run_next == 'true'
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  # The rest only run if above are done

  tests:
    runs-on: ubuntu-latest
    needs: initial_checks
    if: needs.initial_checks.outputs.run_next == 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: python -m pip install wheel pytest
    - name: Run tests
      run: pytest tests
